export const SUBMIT_POST = 'SUBMIT_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const REPLY_TO_POST = 'REPLY_TO_POST'